# Site settings
title: Agent Hype
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Marketing Strategies For The Modern Realtor
author: Enrique Medellin
twitter:
  username:
facebook:
  app_id:
  publisher:
logo:
social:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://agent-hype.com" # the base hostname & protocol for your site. Don't let it end in '/' or you'll mess the links up

# Build settings
markdown: kramdown

#Handling Reading
encoding: "utf-8"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

paginate: 6
permalink: none

gems:
  - jemoji
  - octopress-autoprefixer
  - jekyll-paginate
  - jekyll-sitemap
#  - jekyll-seo-tag

# Excludes
exclude:
  - .sass-cache

sass:
  sass_dir: _sass
  style: :nested
