custom_links:
  - title:
    url:
title: 'Agent <span style="font-weight: bold;">Hype</span>'
client:
  market:
  name: Enrique Medellin
  brand: PRG Real Estate
  brokerage: '#'
  address: '1590 Oakland Rd #B104 San Jose, CA 95131'
  phone: 1-408-416-2488
  email: Enrique@realestatePRG.com
  url:
  homeeval: '#contact2'
  homesearch: /homesearch/
  VR_form: 'http://oi.vresp.com?fid=47068f794f'
socials:
  facebook: '#'
  linkedin: 'https://www.linkedin.com/company/paramount-realty-group'
  gplus: 'https://plus.google.com/b/110031575381166777370/110031575381166777370/about'
  youtube: 'https://www.youtube.com/channel/UCMiC_NieOuhzi3qNys7x6Kw'
  twitter: '#'
  instagram: '#'
  pinterest: '#'
  zillow: '#'
  trulia: '#'
  yelp: '#'
  podcast: '#'
review_sm_icons: true
audit_header: false
podcast:
  title: Agent Hype
  categories:
    - category: 'News &amp; Politics'
  image: 'img/podcast.png'
  subtitle: Marketing Strategies For the Modern Realtor
  description: Supe Up Your Real Estate Career
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: Enrique Medellin
images:
  hero_image_path: /img/aerial.jpg
  hero_logo_path: /img/logo.png
  hero_background_hex: '#2f7283'
  client_headshot_path: /img/headshot.png